### PR TITLE
Update cross-account-member module

### PR DESCRIPTION
**Pull request by kumoy**

### CODE REVIEW

**Review by lorengordon — COMMENTED** [review]
@kumoy Tested and works great! Update the changelog, bump the patch version, and should be good to go

**Comment by kumoy** [comment]
> @kumoy Tested and works great! Update the changelog, bump the patch version, and should be good to go

@lorengordon Should the version in the changelog match the bumpversion?

**Comment by lorengordon** [comment]
Yeah, add an entry for 2.0.1 also please. It was a very similar patch set: https://github.com/plus3it/terraform-aws-tardigrade-security-hub/commit/07eacab3ed30dc176dcde93a457b1a2062aaa9d3

Entry can be:

* Eliminates depends_on by retrieving member account_id from account module

**Review by lorengordon — DISMISSED** [review]
Awesome, looks great

**Comment by kumoy** [comment]
@lorengordon yeah I'm trying to get it working. My Docker app just went crazy after trying to update lol Had to factory reset to defaults for Docker and now it's working. Ran the docs/generate and trying to upload the change. 

Once all is bueno, I'll squash the commits

**Review by lorengordon — COMMENTED** [review]
Oops, @kumoy, the docs need to be regenerated also... `make docs/generate`

**Comment by kumoy** [comment]
@lorengordon okay all should be good

**Review by lorengordon — APPROVED** [review]
🚢

**Pull request merged**
