### PR TITLE
Control finding generator

### PR DESCRIPTION
**Pull request by userhas404d**
Hey P3, I ran into an issue with the `member-account` module wanting to update this setting from `STANDARD_CONTROL` to `SECURITY_CONTROL` which looks like its the new default. The rub is that this errors out if you don't have this config option set at the org level. Guessing other users of this module are not going to be operating outside the default but figured I'd open this PR regardless.

### CODE REVIEW

**Comment by lorengordon** [comment]
Thanks @userhas404d! Good to hear from you lol. We pinned to 4.63.0 to avoid this problem for now. We'll need to update the min version to `>= 4.64.0` with this pr, and update the docs.

**Comment by userhas404d** [comment]
> Thanks @userhas404d! Good to hear from you lol. We pinned to 4.63.0 to avoid this problem for now. We'll need to update the min version to `>= 4.64.0` with this pr, and update the docs.

Ah, nice! Updated the provider min version and docs. Re the failed test: guessing that missing email input is intentional?

**Comment by lorengordon** [comment]
>Ah, nice! Updated the provider min version and docs. Re the failed test: guessing that missing email input is intentional?

Kinda intentional, kinda just specific to our own accounts. The email wouldn't work for anyone else, so we don't put a default. But also, the mockstack test isn't required because moto/localstack don't support the APIs. We've been generally leaving the test so we get a visual when moto/localstack updates add the APIs/actions and it starts working.... When it fails and is not required, it gives us a visual we need to run it manually against real AWS.

I'll try to run the tests manually later this week...

Fwiw, I think the default technically is still `STANDARD_CONTROL`, but if your account is a member of an org, and your org-level security hub switched to `SECURITY_CONTROL`, and you tried to upgrade past 4.64.0, then you get an error because the member account can't change the value. Updating the member config to match the management config should address the error, as you found, basically telling terraform _not_ to try to change the member value back... I like setting the default to `SECURITY_CONTROL` though... Security Hub findings are nearly unusable/unmanageable the old way.

**Comment by lorengordon** [comment]
Results of `make test`:

```
❯ AWS_DEFAULT_REGION=us-east-1 TF_VAR_member_email=...... make test PYTEST_ARGS="-v --nomock"
[bootstrap]: Using external tardigrade-ci, skipping auto-init
[pytest//home/loren/git/repos/tardigrade-ci/tests/terraform_pytest] Starting Python tests found under the directory "/home/loren/git/repos/tardigrade-ci/tests/terraform_pytest"
pytest /home/loren/git/repos/tardigrade-ci/tests/terraform_pytest -v --nomock
====================================================================== test session starts =======================================================================
platform linux -- Python 3.8.10, pytest-7.2.2, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /home/loren/git/repos
plugins: mock-3.6.1, cov-2.12.1, travis-fold-1.3.0
collected 2 items

../tardigrade-ci/tests/terraform_pytest/test_terraform_install.py::test_modules[securityhub_cross_account] PASSED                                                                                                                                                                                                                [ 50%]
../tardigrade-ci/tests/terraform_pytest/test_terraform_install.py::test_modules[securityhub_same_account] PASSED                                                                                                                                                                                                                 [100%]

================================================================== 2 passed in 68.03s (0:01:08) ==================================================================
[pytest//home/loren/git/repos/tardigrade-ci/tests/terraform_pytest]: Tests executed!
```

**Pull request merged**
